auto: true
server: true
permalink: none
baseurl: "/"
url: http://ninja.sg
exclude:
- .gitignore
- README.md

owner:
  name: Sebastiaan Deckers
  contact: mailto:seb@ninja.sg
  github: http://git.io/seb

license:
  name: CC-BY-SA
  url: http://creativecommons.org/licenses/by-sa/3.0/

analytics:
  provider: google
  google:
    id: UA-34478357-1

comments:
  provider: disqus
  livefyre:
    site: 313014
  disqus:
    site: ninjasg

prose:
  rooturl: "_posts/articles"
  metadata:
    _posts/articles: |
      title: Your Post Title
      abstract: Short summary of your article.
      published: false
      comments: true
      author_email: seb@ninja.sg
      author: Sebastiaan Deckers
      layout: article
      categories:
      - articles